### PR TITLE
Add position types

### PR DESCRIPTION
**Pull request by fenhl**
**Do not merge yet:** this could use some tests.

Adds a `types::pos` module with `Protocol` impls for `[T; 3] where T: Protocol`, meant to represent 3D coordinates (block positions as well as exact ones). Additionally, a `BlockPos` type encodes `[i32; 3]` positions as the [Position](http://wiki.vg/Data_Types#Position) protocol type.

### CODE REVIEW

**Comment by toqueteos** [comment]
On the phone. proto_len for [i32; 3] is 12 not 8.

**Comment by toqueteos** [comment]
UpdateSign can't be enabled. We still have no Chat type, do we?

**Comment by toqueteos** [comment]
Ok, forget about UpdateSign.

**Comment by fenhl** [comment]
@toqueteos: I'm assuming you're referring to `BlockPos::proto_len`? That is actually 8, since this is the “26 bits of x, 12 bits of y, 26 bits of z” type.

**Comment by toqueteos** [comment]
@fenhl Yup, that's right. Android's GitHub app isn't that great for reviewinh, my bad. I'll clean up comments when I get home.

Seems good to merge but I'm worried about fixed point positions and those triplets multiplied by random values (gaussian, 8, ...)

**Comment by fenhl** [comment]
We can always add `Mul` impls later if that's what you're talking about.

**Comment by toqueteos** [comment]
@fenhl Those are encoding operations.
Example: [Sound Effect (0x29)](http://wiki.vg/Protocol#Sound_Effect) Encode does \* 8, Decode does / 8.
Could this be automatic so we never forget to do it? We can always add some wrappers for read & write I guess...

**Comment by fenhl** [comment]
ah, good point. Those are the fixed-point number types. We will have to implement all of these manually until [integer-parameterized types](https://github.com/rust-lang/rfcs/pull/884) land.

**Comment by toqueteos** [comment]
Ready to merge.

**Comment by fenhl** [comment]
I suppose we can add tests later.

**Pull request merged**
