### PR TITLE
First steps towards single player support

### PR DESCRIPTION
**Pull request by toqueteos**
I've been working on the single player support for hematite_server. I created the PR so we can comment on lines, there's stuff happening just not that visible.
- [x] Rust v1.5
- [ ] `rustfmt`
  - Unfortunately it causes a bit of a mess, we won't use it for now
- [x] Documentation:
  - [ ] Whatever gets added has docs
  - [ ] NON-Goal. Docs for everything I can catch
- [x] List of changes:
  - [x] Got rid of the BLOCK OF SHAME! :tada:
  - [x] Keep Alive based on channels as https://github.com/RichardlL/Tunnul does!
  - [x] First steps towards supporting single player #97
  - [x] `serverbound::KeepAlive` was `i32` instead of `Var<i32>`.
  - [x] `clientbound::PlayerAbilities` being sent twice, with bad params
  - [x] Gamemode set to survival by default, instead of adventure.

/cc @fenhl @RichardlL

### CODE REVIEW

**Comment by fenhl** [comment]
What's with the randomly indented line continuations everywhere?

**Comment by RichardlL** [comment]
Wow, Someones getting work done!

I've was pretty sick last week, but right now I'm working on stuff for nearly implicit type conversion and packet sending.  Also a very cool way of having chunks use **_Much**_ less memory, and near none compression cost (cost less to compress than not) for sending chunks to the client.  No promises, but stay tuned :)

#### I'll review more later, but my initial comments  are:
- Generating a random number for keep alive is useless, as we cant check what it is,(there is no point in having it random anyway) so I just use 0 to de-clutter the code/ dependencies
- The way I'm planning on checking if the client is responding (keep alive resonse)
  - is having the timeout on the TcpStream's read in the general game packet handling loop  to 30 seconds (Default keepalive timeout)
  - if the read fails (times out/ stream died, doing it this way handles all cases of disconnect)  
    - Call  shutdown method on the client's tcpstream to "notify" the keepalive thread, in case it was do to timout
    - handle player disconnect / saving / Saying "Player disconnected", etc

On another note, Why Single Player first? It seems that it would be much easier to implement Multi -> single than the other way around.

#### Also, was it @fenhl who wanted to avoid encoding/decoding during single player?

I haven't done much research into it, but it seems an easy way to do this is to:
- Compile two server binaries, one single-player and one multiplayer
- Have an environmental variable to switch which modules are used, single or multiplayer, but they are named the same;

**E.G.**

```
if mode == multi_player {
     mod multi_player::types::{string,chat, etc};
     use multi_player::types::{string,chat, etc};
} else {
     mod single_player::types::{string,chat, etc};
     use single_player::types::{string,chat, etc};
}
...
let string = string::convert_string();
```

This way nothing would have to be reimplemented

For most single player statically sized types, it would just look like this

```
fn convert_from_minecraft_format(input: Type) -> Type {
    return input;
}
```

And with Link time optimization enabled the entire function would just be removed

Abnormalities like Varints just be transmuting from a fixed size byte array of 4  (size of i32) , Strings could just be prefixed with i32 rather than a varint and transmuted, (which is also free!), etc.

**Comment by toqueteos** [comment]
Single player it's just the name, this branch right now allows more than one player to log in and do its thing but because we lack proper entity handling they won't see each other (I'm not actually sure if they can see or not, I need to try this). There are no protocol differences between single and multiplayer, at least that I'm aware of.

> Generating a random number for keep alive is useless, as we cant check what it is,(there is no point in having it random anyway) so I just use 0 to de-clutter the code/ dependencies

Right now it's outputting the number and we should check it because that's what the protocol spec states, that KeepAlive number ids should match. We can always hardcode the value or make it something incremental (this is actually a great idea which might be useful in the future for reproducing bugs).

**Comment by toqueteos** [comment]
@fenhl 

> What's with the randomly indented line continuations everywhere?

That must be `rustfmt`. Can you give me a specific line?

**Comment by toqueteos** [comment]
WIP commit is gone! Still lots of stuff left to do :tada:

I improved `Server::keep_alive_loop` so it checks multiple times for sends on the `TcpStream` channel and then sends all the KeepAlive packets in batch.

**EDIT:** Tests currently failing because of `#[deny(unused_assignments)]`. If I don't assign it a default value it also warns so... Maybe doing it in a more functional way will solve it... _thinking about it_

**EDIT2:** Duh, solved it. I was doing a stupid assigment which was totally unnecessary.

**EDIT3:** Fixed stats vec! indentation.

**Comment by fenhl** [comment]
@toqueteos line 67 in src/packet.rs, for example.

**Edit:** also the packet macros.

**Comment by toqueteos** [comment]
@fenhl Yep, that's rustfmt. It can be solved by declaring packets first and then writing them instead of calling `try!(Packet{ ... }).write(&mut stream)`

**Comment by fenhl** [comment]
I'd rather avoid using rustfmt as long as it produces this kind of output.

**Comment by RichardlL** [comment]
@toqueteos
Very Nice Man! 

You can fire off code like crazy. I can do like 100 lines a day, and have no discipline for error handling. "Just panic, each user has their own thread, lol" 

I finally drew up the plans for how chunks being stored in ram will work, and wanted your guy's opinions on it

Rather than storing blocks, I was planning on storing "structures".  These are very simple, but to have a hierarchy to assemble the map

The structure layout would be
```
Block Id / Data | starting position | ending position
----------------------------------------------
    2 bytes     |      u16          | u16
``` 
BlockID is the same as how its sent to the client (u16 = (id << 4 )| data)
Starting position is the yxz coordinate, non array  (u16 = y * 16 + x * 16 + z * 16)
and ending position is where that specific blocks would stop being repeated

Each chunk would have a vector of many of these structures

Each structure shadows  all the ones before it. If you want to send blocks to the player, you find in the vector where the block is valid, then find where it might be shadowed, and the difference to the player's stream, so a one demensional cross section of a tree  would be
````
  air | 0 | 16
-------------
leaves | 5 | 14
-------------
wood | 9 | 10
````

and the algorithm process would look like 
````
let current_position = 0;
let mut length = 0;
while current_position < end_of chunk {
    for z in (structure backwords) {
        if current position is in (z startingposition - i.ending position){
            for a in structure.last..structure.z  { 
                // If a new structure overshadows part of this one
                if a.starting_posisition is < z.endingposition {
                    length = a.starting - z.starting position
                    current_position += length;
                    break; (to outside of first for (inside while))
                }
             }
            // otherwise we use the whole structure
             length = z.end_position - z.starting_position;
             current_position += length
        }
      }
    *
      for 0..length {
          stream.write(z.data) 
      }
}
````
*We wouldnt actually use a loop here, see https://en.wikipedia.org/wiki/DEFLATE#Duplicate_string_elimination

Which would end up making the tree cross section look like this
````
----####X####--
where 
- air
# leaves
X woood
````

We have spend cpu cycles compress the data before we send it to the player anyway, So why not take advantage of it to be stored in ram?

**Comment by fenhl** [comment]
Ideally, we would use the same memory layout the 1.9 snapshots use in their chunk data packet.

**Comment by RichardlL** [comment]
Wait I did my calculations wrong.  Looks like at a render distance of 10, the new format would only use 3mb of data. 

Well all that planning was useless, haha.

**Comment by fenhl** [comment]
This should be a separate issue btw.

**Comment by toqueteos** [comment]
@fenhl Could you find a suitable rustfmt config so we don't ditch it entirely? The purpose of rustfmt is getting rid of styling discussions and having uniform code style all over a project is a good thing.

**Comment by fenhl** [comment]
@toqueteos I haven't used rustfmt yet, but I doubt this exists given the tool's notoriously bad macro handling. At this point, I think we can still manage style manually. In fact, I might open a style review PR soon.

**Comment by toqueteos** [comment]
@fenhl If it doesn't exist, create one! It's simple. Crate a `rustfmt.toml` in the project root and tune it as you like. `rustfmt --config-help` shows you the current configurable options.

**Comment by toqueteos** [comment]
I'm working on the un-rustfmt-ization and finishing #76

**Comment by toqueteos** [comment]
It's been 6 years. I'm closing this. If anybody wants to continue this, feel free to do it.

**Pull request closed without merging**
