### PR TITLE
Provide proper tests for server.properties

### PR DESCRIPTION
**Pull request by toqueteos**
This is a follow-up PR of https://github.com/PistonDevelopers/hematite_server/pull/102

Changes:
- `Properties` struct now derives `PartialEq` deriving so we can use the `assert_eq!` macro in the tests.
- `Properties::load` now returns an `io::Error` if it finds an unknown property.

/cc @fenhl

### CODE REVIEW

**Comment by toqueteos** [comment]
Woops, needs a rebase because we just merged #102 D'oh!

**EDIT:** Done!

**Comment by fenhl** [comment]
It's funny how this test passes even though the parsing is completely broken (#104). Maybe add another equivalent test for a custom server.properties file?

**Comment by toqueteos** [comment]
Rebased with latest master (contains #104).

**Comment by toqueteos** [comment]
Force pushed with three tests and a new commit message:
- [x] `Properties::load/save` using `Properties::default`.
- [x] `Properties::load/save` using `Properties::default` + `Properties.server_port=25570` (not default value).
- [x] `Properties::load` with unknown properties failing as expected.

**Comment by toqueteos** [comment]
Ping @fenhl

**Pull request merged**
