### PR TITLE
Fix compile warnings and move some conversion methods to std::convert trait impls

### PR DESCRIPTION
**Pull request by fenhl**
Leaving this open for discussion since  `std::convert` seems to be controversial.

cc @eddyb

### CODE REVIEW

**Comment by toqueteos** [comment]
`From` and `AsRef` seem pretty awesome, they clean code a lot.

**Comment by atheriel** [comment]
Oh man, the new `From<T>` thing is great!

**Comment by toqueteos** [comment]
Any updates on this?

**Comment by fenhl** [comment]
Since @eddyb hasn't commented on this, I guess it's good to merge?

**Pull request merged**
