### PR TITLE
Update rustc-serialize import to new syntax

### PR DESCRIPTION
**Pull request by fenhl**
See rust-lang/rfcs#940 for details.

### CODE REVIEW

**Comment by toqueteos** [comment]
Finally! No more renames because of `-`.

**Comment by fenhl** [comment]
We could even rename to `hematite-server`.

**Comment by toqueteos** [comment]
And hem-nbt?

**Comment by fenhl** [comment]
I prefer `nbt` there, since it's probably the only NBT lib out there and might even go on crates.io soon.

**Pull request merged**
