### PR TITLE
Add request-ping reverse slp test

### PR DESCRIPTION
**Pull request by toqueteos**

### CODE REVIEW

**Comment by fenhl** [comment]
A `should_panic` test for something that may or may not actually be intended to work? Big :-1: from me.

**Comment by toqueteos** [comment]
It works that way, the test is intended for `minecraft_server.jar` which is our reference. If that doesn't work then it means Protocol is not well documented.

It uses `should_panic` because when `.unwrap` is called you get an EOF error. An equality test would work too.

**Comment by fenhl** [comment]
I was mistaken on how server list ping is supposed to work. Feel free to merge.

**Comment by toqueteos** [comment]
I'm curious, what has changed?

**Comment by fenhl** [comment]
Servers are supposed to disconnect after sending the pong. Clients will never close the connection first. This means that the order has to be the same every time.

**Pull request merged**
