### PR TITLE
Refactored using `clippy` and `rustfmt`.

### PR DESCRIPTION
**Pull request by cedws**
I cleaned up a bit by running `clippy` and `rustfmt` on the code. Clippy still warns about some lints that I have been unable to fix.

### CODE REVIEW

**Review by fenhl — COMMENTED** [review]
While there are many good changes here, I disagree with most of the changes, especially trailing commas in struct/enum members and match arms, the added newlines in match arms with braces, and formatting of long where and if-let clauses. Can rustfmt be configured for varying formatting styles?

(As a side note, I'm surprised Clippy doesn't have a lint for migrating `try!` to `?`.)

**Comment by cedws** [comment]
@fenhl Thanks for taking a look. Whilst I understand you have preferences on how Rust code should be styled, `rustfmt` is opinionated for a reason. I don't agree with *all* of the formatting changes either, but it's important that we have a strict and consistent code style in the Rust community.

**Comment by cedws** [comment]
@fenhl Hi, just going through some unmerged PRs. What should with do with this? You are welcome to close it if you are unhappy with these changes. 

Thanks.

**Comment by fenhl** [comment]
This should stay open until someone has the time to go through and apply the improvements only. Since this project is pretty dead, I don't expect this to happen any time soon.

**Comment by cedws** [comment]
I'm going to close this, as the project is inactive and it probably isn't worth the risk of breaking anything at this point. Thanks.

**Pull request closed without merging**
