### PR TITLE
Nbt enc/decoding impl.

### PR DESCRIPTION
**Pull request by toqueteos**
Quirks:
- Currently doesn't compile because of move errors.
- Quite unidiomatic.
- Room for lots of improvement.

/cc @eddyb @fenhl _Anyone else?_

### CODE REVIEW

**Comment by toqueteos** [comment]
~~I forgot to update to our new `Protocol` signature (proto_decode lost `plen` arg).~~

Fixed.

**Comment by toqueteos** [comment]
The only way I found to fix move problems is using `.clone()`. Lines: 110, 208, 333.

**Comment by fenhl** [comment]
Regarding the move errors: why does `write_compound` etc take a reference when `proto_encode` doesn't?

**Comment by toqueteos** [comment]
`Nbt` and `List` can't be `Copy` (because of `String`, `Vec<Vec<i8>>` and `Vec<Vec<i32>>`), so if values are used then everything complains about values being moved. Also `.iter()` returns `&T`.

Example: http://is.gd/n7K7Va (two consecutive calls to `use_compound` may be clearer)

We have to use references all over the place and clones for some `proto_encode` calls. :disappointed: 

I think we could also use `Rc` but I'm not entirely sure.

**Comment by toqueteos** [comment]
@eddyb r?

**Comment by fenhl** [comment]
Hang on, I'm trying to get something else to work. Since `proto_encode` takes values by move it's not a problem to move out of the values instead of using `.iter`.

**Pull request merged**
