### PR TITLE
Add EntitySelector type

### PR DESCRIPTION
**Pull request by fenhl**
This adds an `EntitySelector` type which represents selectors like `@p` or `@e[0,64,0,80,type=Creeper,c=-4]`. It supports decoding via [`FromStr`](http://doc.rust-lang.org/std/str/trait.FromStr.html), and encoding via [`Into<String>`](http://doc.rust-lang.org/std/convert/trait.Into.html).

### CODE REVIEW

**Comment by toqueteos** [comment]
Awesome PR! :confetti_ball:

it's just `src/types/chat.rs:17:5` the thing Travis is complaining about though.

Not having support for compiler plugins on stable is a shame :disappointed:.

**Comment by fenhl** [comment]
That's not the only problem. I have included a test which is supposed to make sure that all basic selectors (`@a`, `@e`, `@p`, `@r`) are enoded as exactly those strings. It is currently failing because the encoding function never uses `@a` or `@p`.

**Comment by toqueteos** [comment]
That's not showing up on Travis, weird...

**Comment by fenhl** [comment]
The error in `chat.rs` is causing the compiler to abort. I'm testing with that line commented out.

**Comment by fenhl** [comment]
Tests are passing now, including a new one which tests the decoding of `@e[0,64,0,80,type=Creeper,c=-4]`.

**Pull request merged**
