### PR TITLE
Introduce a compiler plugin for deriving NBT format serializations for structs.

### PR DESCRIPTION
**Pull request by atheriel**
This PR also reorganizes the `nbt` crate, and lays some of the groundwork for faster overall serialization.

### CODE REVIEW

**Comment by atheriel** [comment]
Travis seems to be freaking out about `rust-serialize`. I don't think `nbt` even builds on it, anyway.

**Comment by atheriel** [comment]
I'm going to add a few more pieces (better docs, more comments, some bugs) before merging.

**Comment by eddyb** [comment]
I wonder what part of this is incompatible with `serde` (if any).
Other thoughts: shouldn't this be a separate library?
And that awful `Vec<NbtValue>` for lists is still there...

**Comment by atheriel** [comment]
I have a (fairly complete) implementation compatible with `serde`, which was my original approach. But the trouble is that `serde` is really designed to be able to serialize _all_ Rust types -- which NBT is really not designed for. So you end up writing throwing errors at runtime (which is how `serde` handles this), which didn't make much ergonomic sense to me.

The internal design of this implementation is very much inspired by `serde`, though.

The `Vec<NbtValue>` will one day be gone... I'm hoping to bury `NbtBlob` and use `NbtFmt` as much as possible, kind of like how `serde::json` works with `Json` being the little-used generic.

**Comment by atheriel** [comment]
Sorry, I meant [`Value`](http://serde-rs.github.io/serde/serde/json/value/enum.Value.html), not `Json`.

**Comment by fenhl** [comment]
The nbt crate has been moved to [its own repo](https://github.com/PistonDevelopers/hematite_nbt), please send a pull request there.

(Also, you might want to keep feature branches under your own fork, so that Travis CI won't flood the channel with their results.)

**Comment by atheriel** [comment]
@fenhl Oh shit, I didn't even notice that. No wonder it won't merge. I'll cherry pick them into that repo at some point this weekend.

**Comment by atheriel** [comment]
Also, since Travis builds PRs, it creates exactly the same amount of flooding, no?

**Comment by fenhl** [comment]
No, PR build results aren't forwarded to IRC.

**Comment by atheriel** [comment]
Fair enough.

**Pull request closed without merging**
